### Fetch customers
GET http://localhost:8201/customers
Content-Type: application/json
Authorization: Basic user the_cake

### Fetch a customer
GET http://localhost:8201/customers/1
Authorization: Basic user the_cake

### Create a customer
POST http://localhost:8201/customers
Content-Type: application/json
Authorization: Basic admin is_a_lie

{
  "username": "bobby",
  "firstName": "bob",
  "lastName": "loblaw",
  "passportNumber": "MEOW",
  "email": "bob@loblaw.net",
  "phoneNumber": "0000"
}