### Fetch all flights
GET http://localhost:8202/flights
Content-Type: application/json
#Authorization: Basic user the_cake

### Fetch a specific flight
GET http://localhost:8202/flights/1
#Authorization: Basic user the_cake

### Fetch flight specials
GET http://localhost:8202/flights/specials
Authorization: Basic loyalty_user the_cheese_cake

### Create a flight
POST http://localhost:8202/flights
Content-Type: application/json
Authorization: Basic admin is_a_lie

{
  "flightNumber": "999",
  "origin": "JNB",
  "destination": "CPT",
  "departureTime": "2025-06-01T20:00:00",
  "arrivalTime": "2025-06-01T22:00:00",
  "seatsAvailable": 999,
  "seatCost": 999.99
}